FROM php:8.3-fpm

# Arguments defined in docker-compose
ARG user
ARG uid
ARG app_mode
ARG xdebug_enabled

COPY "./deploy/fpm/conf.d/php.ini-$app_mode" "$PHP_INI_DIR/php.ini"
COPY "./deploy/fpm/conf.d/www.conf-$app_mode" "/usr/local/etc/php-fpm.d/www.conf"
COPY "./deploy/fpm/conf.d/xdebug.ini" "/tmp/conf.d/xdebug.ini"

# Install system dependencies
RUN apt-get update && apt-get install -y \
    curl \
    libjpeg-dev \
    libwebp-dev \
    libpq-dev \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    libzip-dev \
    zip \
    unzip \
    sudo

# Clear cache
RUN apt-get clean && rm -rf /var/lib/apt/lists/*

# Install PHP extensions
RUN docker-php-ext-install pdo pdo_pgsql pdo_mysql mbstring exif pcntl bcmath gd zip opcache sockets intl > /dev/null

# Install XDebug only in local development mode
RUN if [ "$xdebug_enabled" = "true" ]; then \
        cp /tmp/conf.d/xdebug.ini $PHP_INI_DIR/conf.d/docker-php-ext-xdebug.ini && \
        pecl install xdebug && \
        docker-php-ext-enable xdebug; \
    fi

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN mkdir -p /home/$user/.composer && \
    chown -R $user:$user /home/$user

# Set working directory
WORKDIR /var/www

USER $user
